spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankmvp
    username: postgres
    password: Nikhil@2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    show-sql: true

  sql:
    init:
      enabled: false   # completely disables SQL init

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE   # shows bound parameter values
    org.springframework.boot.autoconfigure: INFO

server:
  port: 8080
