spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankmvp
    username: postgres
    password: Nikhil@2
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none     # no schema changes yet
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: never        # avoid running schema.sql accidentally
server:
  port: 8080
